name: Nuke environment
on:
  schedule:
    - cron: '* 3 * * *'

jobs:
  nuke:
    name: Clean testing environment
    runs-on: ubuntu-latest
    container:
      image: quay.io/rebuy/aws-nuke
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Nuke
        run: echo gp-testing | aws-nuke -c ./.scripts/nuke.yml -q --no-dry-run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
